name: 🚀 Deploy ke Niagahosting

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.rosybrown-yak-159319.hostingersite.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: public_html/feelscoffe/
